### PR TITLE
[General] Update project dependencies & codebase.

### PR DESCRIPTION
**Pull request by sunshinejr**
Hey guys! First of all thanks for this project, learned a lot from it! 👏 

In this PR I upgraded ReSwift & ReSwiftRouter dependencies and adjusted codebase to use the new APIs where needed. Additionally there was a problem with 2 constants: `githubToken` & `githubSecret`, which (via Readme & other parts of the code) should be named `githubClientId` & `githubClientSecret`, so I've renamed it as well. Hope that this PR seems alright! 

_Please bear in mind that I'm new to ReSwift, ReSwiftRouter & I don't use Carthage at all, so I might have used something wrong._ 

Cheers! 🎉

### CODE REVIEW

**Comment by Ben-G** [comment]
@sunshinejr Thanks a lot for the updates! This is a huge help 🎉 

While you're at it; would you mind also updating the test files to the latest APIs such that we can run the existing unit tests?

**Comment by sunshinejr** [comment]
Sure. Gonna tackle that one and let you know :)

**Comment by sunshinejr** [comment]
Done, @Ben-G. Should be all right now :)

**Comment by Ben-G** [comment]
Thanks a bunch @sunshinejr! 🎉 
As all contributors I will invite you to the ReSwift org. That will make it easier for you to contribute in future, if you are interested!

**Pull request merged**
